### ISSUE TITLE
支持排除特定key（高优先级）

### ISSUE THREAD

**Issue by klzami** [imroc/zk2etcd#1]
## 1. 现状

当前版本把zk里所有/dubbo的key都同步到了etcd，包括：注册关系、rpc公共配置，这种模式会造成冲突。

rpc公共配置每个机房都不相同，但却是同样的key，例如：``/dubbo/config/pro/dubbo.properties``。

因此，如同步过去，会导致【其它机房的配置 把 新机房的配置 冲掉】。

## 2. 诉求

因此，需要支持排除掉部分key，例如：--zookeeper-exclude=/dubbo/config/**。

这个需求优先级很高，如果不支持的话，上生产环境后都跑不通。

**Comment by imroc** [comment]
已支持，详见 v0.9.0 的 changlog
